[project]
id = "hnencfkdsyiwtvktdvzy"

[functions.create-user-by-moderator]
verify_jwt = false

[functions.process-registrations]
verify_jwt = false

[functions.abacate-webhook]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = true

[functions.create-mercadopago-payment]
verify_jwt = true

[functions.validate-affiliate-commissions]
verify_jwt = false

[functions.generate-temp-certificate]
verify_jwt = false

[functions.create-pendrive-subscription]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = false
